export const OPEN_DRAWER = 'OPEN_DRAWER';
export const GET_PORTFOLIO_REQUEST = 'GET_PORTFOLIO_REQUEST';
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS';
export const GET_PORTFOLIO_FAIL = 'GET_PORTFOLIO_FAIL';
export const SET_PORTFOLIO_MODAL = 'SET_PORTFOLIO_MODAL';